export const ProductDummyData = [
  {
    id: "1",
    productName: "Lovely Dress",
    productPrice: 103,
    productAddedDate: "23,10,2023",
    productCategory: "Women Fashion",
  },
  {
    id: "2",
    productName: "Stylish Shoes",
    productPrice: 75,
    productAddedDate: "15,11,2023",
    productCategory: "Footwear",
  },
  {
    id: "3",
    productName: "Tech Gadgets",
    productPrice: 299,
    productAddedDate: "05,12,2023",
    productCategory: "Electronics",
  },
  {
    id: "4",
    productName: "Classic Watch",
    productPrice: 150,
    productAddedDate: "18,01,2024",
    productCategory: "Accessories",
  },
  {
    id: "5",
    productName: "Cozy Sweater",
    productPrice: 85,
    productAddedDate: "02,02,2024",
    productCategory: "Winter Apparel",
  },
  {
    id: "6",
    productName: "Healthy Snacks Box",
    productPrice: 30,
    productAddedDate: "12,03,2024",
    productCategory: "Food & Beverages",
  },
  {
    id: "7",
    productName: "Gaming Mouse",
    productPrice: 55,
    productAddedDate: "25,04,2024",
    productCategory: "Gaming Accessories",
  },
  {
    id: "8",
    productName: "Vintage Bookshelf",
    productPrice: 220,
    productAddedDate: "08,05,2024",
    productCategory: "Home Furniture",
  },
  {
    id: "9",
    productName: "Outdoor Tent",
    productPrice: 120,
    productAddedDate: "17,06,2024",
    productCategory: "Camping Gear",
  },
  {
    id: "10",
    productName: "Smartphone Holder",
    productPrice: 15,
    productAddedDate: "30,07,2024",
    productCategory: "Mobile Accessories",
  },
  {
    id: "11",
    productName: "Artificial Plants Set",
    productPrice: 40,
    productAddedDate: "12,08,2024",
    productCategory: "Home Decor",
  },
  {
    id: "12",
    productName: "Fitness Tracker",
    productPrice: 80,
    productAddedDate: "28,09,2024",
    productCategory: "Fitness Gadgets",
  },
  {
    id: "13",
    productName: "Leather Wallet",
    productPrice: 50,
    productAddedDate: "14,10,2024",
    productCategory: "Fashion Accessories",
  },
  {
    id: "14",
    productName: "Desk Organizer",
    productPrice: 25,
    productAddedDate: "26,11,2024",
    productCategory: "Office Supplies",
  },
  {
    id: "15",
    productName: "Wireless Earbuds",
    productPrice: 70,
    productAddedDate: "09,12,2024",
    productCategory: "Audio Gadgets",
  },
  {
    id: "16",
    productName: "Cotton Bed Sheets",
    productPrice: 55,
    productAddedDate: "21,01,2025",
    productCategory: "Bedding",
  },
  {
    id: "17",
    productName: "Travel Backpack",
    productPrice: 90,
    productAddedDate: "03,02,2025",
    productCategory: "Travel Essentials",
  },
  {
    id: "18",
    productName: "Coffee Maker",
    productPrice: 120,
    productAddedDate: "15,03,2025",
    productCategory: "Kitchen Appliances",
  },
  {
    id: "19",
    productName: "Smart Thermostat",
    productPrice: 180,
    productAddedDate: "28,04,2025",
    productCategory: "Smart Home Devices",
  },
  {
    id: "20",
    productName: "Canvas Art Painting",
    productPrice: 65,
    productAddedDate: "10,05,2025",
    productCategory: "Art & Decor",
  },
];
